# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean install -DskipTests=true
      
    - name: where am I
      run: |
        pwd
        ls target/rpm/dhis-integration/RPMS/noarch
    - name: where am I
      run: |
        pwd
        ls target/rpm/dhis-integration/RPMS/noarch
    - name: push dhis-integration to other branch
      run: |
        cd target/rpm/dhis-integration/RPMS/noarch
        git config --global user.email "la.mphatsi@gmail.com"
        git config --global user.name "lmphatsi"
        git init
        git branch -m main
        git add .
        git commit -m "release dhis-integration rpm"
        git remote add github https://${{ secrets.DHIS_INTEGRATION_KEY }}@github.com/lmphatsi/test-dhis-integration-rpms.git
        git push -f github main
